[build]
  # 构建命令
  command = "cd docs && npm run build"
  # 发布目录
  publish = "docs/.vitepress/dist"
  # Node.js 版本
  environment = { NODE_VERSION = "20" }

[build.environment]
  NODE_ENV = "production"

# 重定向规则，用于 SPA 路由
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 缓存设置
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# 预渲染设置（可选）
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true

# 插件配置（可选）
# [[plugins]]
#   package = "netlify-plugin-lighthouse"